### ISSUE TITLE
typo3 / powermail version compatibility

### ISSUE THREAD

**Issue by macjohnny** [bithost-gmbh/powermail_fastexport#1]
@maechler the code should be compatible with current powermail versions, so I suggest to have the current powermail versions included in the ext_emconf.php, otherwise it shows a dependency of powermail `3.2.0` in https://extensions.typo3.org/extension/powermail_fastexport/

Moreover, the TYPO3 version compatibility should be changed to `7-9`

**Comment by maechler** [comment]
@macjohnny You are absolutely right. I will change and test this in the upcoming weeks as we upgrade a TYPO3 site using this extension to TYPO3 `v8`.
