### ISSUE TITLE
powermail version compatibility

### ISSUE THREAD

**Issue by rubyonair** [bithost-gmbh/powermail_fastexport#4]
Hi maechler,

are you planning any further development regarding the compatibility of the Powermail version?

Regards, Janine

**Comment by macjohnny** [comment]
did you test it with a newer powermail version? were there any problems? if so, would you be interested to adapt the code of powermail_fastexport and file a PR?

**Comment by maechler** [comment]
@rubyonair We will soon test it with powermail `v7`, but any contribution from you would be appreciated!

**Comment by maechler** [comment]
It seems to already be working with powermail `v7`, I just updated the version constraints and created a new release `v1.0.5`. It will soon be available in TER.
